server:
  port: 8050
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration

lms:
  openapi:
    stage-url: http://localhost:${server.port}
    prod-url: http://localhost:${server.port}

springdoc:
  api-docs:
    path: /lms-common-service/v3/api-docs
  swagger-ui:
    path: /lms-common-service/swagger-ui.html