server:
  port: 8055

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    gateway:
      routes:
        - id: lms-auth-service
          uri: lb:http://LMS-AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: lms-common-service
          uri: lb:http://LMS-COMMON-SERVICE
          predicates:
            - Path=/commons/**
          filters:
            - AuthenticationFilter

        - id: lms-operation-service
          uri: lb://http://LMS-OPERATION-SERVICE
          predicates:
            - Path=/operations/**
          filters:
            - AuthenticationFilter

        - id: lms-discussion-service
          uri: lb://LMS-DISCUSSION-SERVICE
          predicates:
            - Path=/discussions/**
          filters:
            - AuthenticationFilter

lms:
  security:
    jwt:
      secret-key: dd38da31ac47e34a6c1753ac559de1448996fc2c2e5fae28f2651c5108ed14f2
  openapi:
    stage-url: http://localhost:${server.port}
    prod-url: http://localhost:${server.port}