server:
  port: 8054

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: registrationGroup,enrollGroup,assignGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: registrationSuccessNotificationRequest:com.bjet.aki.lms.domain.RegistrationSuccessNotificationRequest
  mail:
    host: smtp.gmail.com
    port: 587
    username: bjet.aki.info@gmail.com
    password: ehbh zgxi pzft wasi
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:3000

lms:
  deployment:
    host: ${LMS_HOST:http://localhost:3000}
  template_dir: ${LMS_TEMPLATE_DIR:/}
