spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pdb:5432/lms
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root123}
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092
