eureka:
  instance:
    preferIpAddress: true
    hostname: ${DISCOVERY_HOSTNAME:eureka-0}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_CLIENT:http://eureka:8761/eureka/}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:pdb}:5432/lms
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root123}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:lms-kafka}:9092
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:lms-kafka}:9092
