eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:pdb}:5432/lms
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root123}
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
