spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: lms-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
      - url: /lms-common-service/v3/api-docs
        name: Common Service
      - url: /lms-operation-service/v3/api-docs
        name: Operation Service
      - url: /lms-auth-service/v3/api-docs
        name: Auth Service

